export const SOCKET_EVENTS = {
  connect: 'connection',
  disconnect: 'disconnection',
  afterDisconnect: 'afterDisconnect',
  joinGame: 'join_game',
  hostGame: 'host_game',
  startGame: 'start_game',
  gameStarted: 'game_started',
  isHosting: 'is_hosting',
  hasJoined: 'has_joined',
  enterDisallowed: 'enter_disallowed',
  playerMove: 'player_move',
  updateBoard: 'update_board',
  gameOver: 'game_over',
  playAgain: 'play_again',
  quitGame: 'quit_game',
  reloadWindow: 'reload_window',
  reloadGame: 'reload_game',
};
